DATA:
        ROOT: 'xclip/data/videos'
        TRAIN_FILE: 'xclip/data/videos/train.txt'
        VAL_FILE: 'xclip/data/videos/val.txt'
        DATASET: fit101
        NUM_FRAMES: 32
        NUM_CLASSES: 5
        LABEL_LIST: 'xclip/data/videos/labels.csv'
MODEL:
        ARCH: ViT-B/16
TRAIN:
        BATCH_SIZE: 4
        ACCUMULATION_STEPS: 2
        EPOCHS: 50
        LR: 2.e-6