DATA:
        ROOT: 'data/videos'
        TRAIN_FILE: 'data/videos/train.txt'
        VAL_FILE: 'data/videos/val.txt'
        DATASET: fit101
        NUM_FRAMES: 8
        NUM_CLASSES: 5
        LABEL_LIST: 'data/videos/labels.csv'
MODEL:
        ARCH: ViT-B/16
TRAIN:
        BATCH_SIZE: 5
        ACCUMULATION_STEPS: 2
        EPOCHS: 50
        LR: 2.e-6
SAVE_FREQ: 10